# Generated by Django 3.1.6 on 2021-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dishes_ingredient', models.TextField(max_length=200)),
                ('Dishes_name', models.CharField(max_length=100)),
                ('Dishes_price', models.FloatField()),
                ('Dishes_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('Dishes_discount', models.FloatField()),
                ('Dishes_category', models.CharField(max_length=100)),
            ],
        ),
    ]
