# Generated by Django 3.1.6 on 2021-03-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='Restaurant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
