# Generated by Django 3.1.6 on 2021-03-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishes_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='Restaurant_id',
        ),
    ]
