# Generated by Django 3.1.6 on 2021-03-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dishes_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='Dishes_category',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='Dishes_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
