# Generated by Django 3.1.6 on 2021-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=50)),
                ('customer_address', models.TextField(max_length=200)),
                ('customer_email', models.EmailField(max_length=62)),
                ('customer_phoneNo', models.CharField(max_length=20)),
                ('customer_accountCreated', models.DateTimeField(auto_now_add=True)),
                ('customer_profilePicture', models.ImageField(blank=True, null=True, upload_to='')),
                ('customer_dateOfBirth', models.DateTimeField()),
                ('customer_rating', models.FloatField(blank=True)),
            ],
        ),
    ]
