# Generated by Django 3.1.6 on 2021-03-06 11:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_password', models.CharField(max_length=100000)),
                ('customer_address', models.TextField(max_length=200)),
                ('customer_email', models.EmailField(max_length=62, unique=True)),
                ('customer_phoneNo', models.CharField(max_length=20)),
                ('customer_accountCreated', models.DateTimeField(auto_now_add=True)),
                ('customer_profilePicture', models.ImageField(blank=True, null=True, upload_to='static/customer_image')),
                ('customer_dateOfBirth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
