# Generated by Django 3.1.6 on 2021-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_accountCreated',
            new_name='accountCreated',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_dateOfBirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phoneNo',
            new_name='phoneNo',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_profilePicture',
            new_name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
    ]
