# Generated by Django 3.1.6 on 2021-02-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_rating',
        ),
    ]
