# Generated by Django 3.1.6 on 2021-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profilePicture',
        ),
    ]
