# Generated by Django 3.1.6 on 2021-02-26 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_customer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_rating',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
