# Generated by Django 3.1.6 on 2021-03-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210306_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_password',
        ),
    ]
