# Generated by Django 3.1.6 on 2021-03-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_customer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_rating',
        ),
    ]
