# Generated by Django 3.1.6 on 2021-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
