# Generated by Django 3.1.6 on 2021-03-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210311_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
    ]
