# Generated by Django 3.1.6 on 2021-03-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_customer_rating'),
        ('dishes', '0001_initial'),
        ('addToCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='Dishes',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='Dishes',
            field=models.ManyToManyField(to='dishes.Dishes'),
        ),
    ]
