# Generated by Django 3.1.6 on 2021-03-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliver', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('addToCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('AddToCart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addToCart.addtocart')),
                ('Deliver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.deliver')),
                ('Restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
