# Generated by Django 3.1.6 on 2021-03-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('deliver', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Deliver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.deliver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
