# Generated by Django 3.1.6 on 2021-03-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0003_remove_dishes_restaurant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes')),
            ],
        ),
    ]
