# Generated by Django 3.1.6 on 2021-03-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20210313_1431'),
        ('category', '0002_auto_20210313_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes'),
        ),
    ]
